### PR TITLE
fix(push): support subscribing multiple times (using broadcast stream)

### PR DESCRIPTION
**Pull request by ben-xD**
Closes https://github.com/ben-xD/push/issues/18

### CODE REVIEW

**Review by kaiquegazola — COMMENTED** [review]
If it's possible to listen to the same stream multiple times, wouldn't it be better to create it as a broadcast instead of converting it to a broadcast in getters?

**Comment by ben-xD** [comment]
Oh wow you're so right! I'll fix it 😬

**Comment by JosephNK0608** [comment]
@ben-xD When will that part be improved and reflected? Now I need it so much.

**Comment by ben-xD** [comment]
@Raphael929, this PR wasn't the best approach. After discussions, I realised a callback based API would be nicer. See https://github.com/ben-xD/push/pull/43

You'll be able to listen multiple times too.

Closing this PR in favour of that one.

**Comment by ben-xD** [comment]
@Raphael929, please try [2.0.0-dev.1](https://pub.dev/packages/push/versions/2.0.0-dev.1). The code is in https://github.com/ben-xD/push/pull/43, and allows you to add callbacks instead of listening to streams.

**Comment by ben-xD** [comment]
> If it's possible to listen to the same stream multiple times, wouldn't it be better to create it as a broadcast instead of converting it to a broadcast in getters?

@kaiquegazola, with this new callback API in [2.0.0-dev.1](https://pub.dev/packages/push/versions/2.0.0-dev.1), you can do that :)

**Pull request closed without merging**
